### ISSUE TITLE
ERROR TOKEN

### ISSUE THREAD

**Issue by ghost** [Giuliopime/Downloadify#1]
Hello, it won't let me enter, it asks me for a token, can I delete that part or what goes there?

**Comment by Giuliopime** [comment]
It's for security reasons, I only give tokens to my irl friends to not get
the platform overloaded. You will need to self host the website, it's just
a nodejs api and a vue spa. I will provide support for docker soon probably.

**Comment by ghost** [comment]
I want to use the desktop application, could I create my own tokens?

**Comment by Giuliopime** [comment]
Yes, clone the repo, start the nodejs api, which by default runs on port 9000. Then change the base url of the desktop app here https://github.com/Giuliopime/Downloadify/blob/master/desktop-app/src/main/java/apiConsumer/APIConsumer.java#L40 to your nodejs api, in your case you can change it to "http://localhost:9000/api/". Then you can run the desktop app normally with java or you can build a .exe file with jpackage but that is a bit harder.

**Comment by Giuliopime** [comment]
You also need to install mongodb though --> https://www.mongodb.com/try/download/community
